buildVariable: false
familyName: Noto Sans Linear A
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans Linear B
  ranges:
  - end: 65843
    start: 65792
recipeProvider: noto
sources:
- NotoSansLinearA.designspace
