buildVariable: false
familyName: Noto Sans Linear A
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans Linear B
  ranges:
    - start: 0x10100
      end: 0x10133
sources:
- NotoSansLinearA.designspace
